# Generated by Django 5.2.4 on 2025-07-15 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='سن')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='تصویر پروفایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تایید')),
                ('code_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال کد')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی')], default='fa', max_length=10, verbose_name='زبان')),
                ('theme', models.CharField(choices=[('dark', 'تاریک'), ('light', 'روشن')], default='dark', max_length=10, verbose_name='تم')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('last_login_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت')),
                ('last_login_device', models.CharField(blank=True, max_length=500, null=True, verbose_name='دستگاه')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ورود')),
                ('profile_picture_captured', models.BooleanField(default=False, verbose_name='تصویر پروفایل آپلود شده')),
                ('profile_picture_capture_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان آپلود تصویر')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='احراز هویت دو مرحله\u200cای')),
                ('login_notifications_enabled', models.BooleanField(default=True, help_text='آیا اعلان\u200cهای ورود برای این کاربر فعال است؟', verbose_name='فعال بودن اعلان\u200cهای ورود')),
                ('last_verification_code_time', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان تایید کد ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز کاربر',
                'verbose_name_plural': 'امتیازهای کاربران',
            },
        ),
    ]
