# Generated by Django 5.2.4 on 2025-07-15 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه چت',
                'verbose_name_plural': 'جلسات چت',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('message_type', models.CharField(choices=[('user', 'پیام کاربر'), ('ai', 'پاسخ هوش مصنوعی'), ('system', 'پیام سیستم')], default='user', max_length=10, verbose_name='نوع پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('is_welcome_message', models.BooleanField(default=False, verbose_name='پیام خوش\u200cآمدگویی')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pimxchat.chatsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ['timestamp'],
            },
        ),
    ]
